genOrderModel:
	goctl model mysql datasource -url="root:root@tcp(127.0.0.1:3306)/looklook_order" -table="*"  -dir="./genModel/order" -cache=true --style=goZero

genPaymentModel:
	goctl model mysql datasource -url="root:root@tcp(127.0.0.1:3306)/looklook_payment" -table="*"  -dir="./genModel/payment" -cache=true --style=goZero

genTravelModel:
	goctl model mysql datasource -url="root:root@tcp(127.0.0.1:3306)/looklook_travel" -table="*"  -dir="./genModel/travel" -cache=true --style=goZero

genUserCenterModel:
	goctl model mysql datasource -url="root:root@tcp(127.0.0.1:3306)/looklook_usercenter" -table="*"  -dir="./genModel/userCenter" -cache=true --style=goZero