.PHONY: genUserCenterService help

genUserCenterService:
	goctl api go -api usercenter.api -dir ../ -style gozero

help:
	@echo  "genUserCenterService --> generate the apis which is usercenter.api defined"