// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitFileReader(path string) (*FileReader, func(), error) {
	fileReader, cleanup, err := NewFileReader(path)
	if err != nil {
		return nil, nil, err
	}
	return fileReader, func() {
		cleanup()
	}, nil
}
