basePath: .
definitions:
  models._ResponsePostList:
    properties:
      code:
        description: 业务响应状态码
        type: integer
      message:
        description: 提示信息
        type: string
    type: object
host: 0.0.0.0
info:
  contact:
    email: yizhigopher@foxmail.com
    name: yizhigopher
    url: http://swagger.io/support
  description: swagger生成接口文档测试
  termsOfService: http://swagger.io/terms
  title: swagger测试学习
  version: "1.0"
paths:
  /posts2:
    get:
      consumes:
      - application/json
      description: 可按社区按时间或分数排序查询帖子列表接口
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      - description: 可以为空
        in: query
        name: community_id
        type: integer
      - description: 排序依据
        example: score
        in: query
        name: order
        type: string
      - description: 页码
        example: 1
        in: query
        name: page
        type: integer
      - description: 每页数据量
        example: 10
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models._ResponsePostList'
      security:
      - ApiKeyAuth: []
      summary: 升级版帖子列表接口
      tags:
      - 帖子相关接口
swagger: "2.0"
