// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitClient(config Config) (*Service, error) {
	apiClient, err := NewAPIClient(config)
	if err != nil {
		return nil, err
	}
	service := NewService(apiClient)
	return service, nil
}
